services:
  portfolio-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "5000"
  portfolio-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - portfolio-backend